# Minimal Nixpacks configuration for Railway
providers = ["python"]

[variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements-railway.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 