"""Add meeting notes table and is_ended field

Revision ID: 6d44727e5661
Revises: db1407af92de
Create Date: 2025-05-28 12:59:00.525467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d44727e5661'
down_revision: Union[str, None] = 'db1407af92de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('is_ended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'is_ended')
    # ### end Alembic commands ###
